# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DeteksiUang.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 606)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#121212;\n"
"    background: url(:/bg/Deteksi Nominal Mata Uang.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GambarMataUang = QtWidgets.QLabel(self.centralwidget)
        self.GambarMataUang.setGeometry(QtCore.QRect(110, 140, 591, 271))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.GambarMataUang.setFont(font)
        self.GambarMataUang.setStyleSheet("QLabel {\n"
"    border : 1px solid #2b4d70;\n"
"    color : #2b4d70;\n"
"}")
        self.GambarMataUang.setAlignment(QtCore.Qt.AlignCenter)
        self.GambarMataUang.setObjectName("GambarMataUang")
        self.PilihUangButton = QtWidgets.QPushButton(self.centralwidget)
        self.PilihUangButton.setGeometry(QtCore.QRect(220, 430, 131, 41))
        self.PilihUangButton.setStyleSheet("QPushButton {\n"
"  background-color: #2b4d70;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 12px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  flex: 0 0 auto;\n"
"  font-family: \"Inter var\",ui-sans-serif,system-ui,-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.125rem;\n"
"  font-weight: 600;\n"
"  line-height: 1.5rem;\n"
"  padding: .75rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none #6B7280 solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition-duration: .2s;\n"
"  transition-property: background-color,border-color,color,fill,stroke;\n"
"  transition-timing-function: cubic-bezier(.4, 0, 0.2, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: auto;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border: 3px solid #a0a2a4;\n"
"    background-color: #374151;\n"
"    opacity : 0.75;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 3px solid black;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.PilihUangButton.setObjectName("PilihUangButton")
        self.DeteksiButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeteksiButton.setGeometry(QtCore.QRect(490, 430, 131, 41))
        self.DeteksiButton.setStyleSheet("QPushButton {\n"
"  background-color: #2b4d70;\n"
"  border: 1px solid transparent;\n"
"  border-radius: 12px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  flex: 0 0 auto;\n"
"  font-family: \"Inter var\",ui-sans-serif,system-ui,-apple-system,system-ui,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n"
"  font-size: 1.125rem;\n"
"  font-weight: 600;\n"
"  line-height: 1.5rem;\n"
"  padding: .75rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none #6B7280 solid;\n"
"  text-decoration-thickness: auto;\n"
"  transition-duration: .2s;\n"
"  transition-property: background-color,border-color,color,fill,stroke;\n"
"  transition-timing-function: cubic-bezier(.4, 0, 0.2, 1);\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: auto;\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    background-color: #374151;\n"
"    opacity : 0.75;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border: 3px solid black;\n"
"}")
        self.DeteksiButton.setObjectName("DeteksiButton")
        self.HasilTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.HasilTextEdit.setGeometry(QtCore.QRect(110, 510, 591, 71))
        self.HasilTextEdit.setStyleSheet("background:white;\n"
"border-radius: 15px;")
        self.HasilTextEdit.setReadOnly(True)
        self.HasilTextEdit.setObjectName("HasilTextEdit")
        self.MataUangLabel = QtWidgets.QLabel(self.centralwidget)
        self.MataUangLabel.setGeometry(QtCore.QRect(110, 120, 101, 21))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.MataUangLabel.setFont(font)
        self.MataUangLabel.setStyleSheet("color : #2b4d70;")
        self.MataUangLabel.setObjectName("MataUangLabel")
        self.HasilLabel = QtWidgets.QLabel(self.centralwidget)
        self.HasilLabel.setGeometry(QtCore.QRect(110, 490, 47, 13))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.HasilLabel.setFont(font)
        self.HasilLabel.setStyleSheet("color : #2b4d70;")
        self.HasilLabel.setObjectName("HasilLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deteksi Nominal Mata Uang"))
        self.GambarMataUang.setText(_translate("MainWindow", "MATA UANG BELUM DIPILIH"))
        self.PilihUangButton.setText(_translate("MainWindow", "Pilih Uang"))
        self.DeteksiButton.setText(_translate("MainWindow", "Deteksi Uang"))
        self.MataUangLabel.setText(_translate("MainWindow", "Mata Uang"))
        self.HasilLabel.setText(_translate("MainWindow", "Hasil"))
# import bg_rc
import bg
